version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  ApplicationStop:
    - location: helper_scripts/app_stop.sh
      timeout: 300
  BeforeInstall:
    - location: helper_scripts/app_install.sh
      runas: root
  AfterInstall:
    - location: helper_scripts/app_post_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: helper_scripts/app_start.sh